const constants = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
  INIT_VIEWER: 'INIT_VIEWER',
  SET_VIEWER_GRAYSCALE_SOURCE: 'SET_VIEWER_GRAYSCALE_SOURCE',
  SET_VIEWER_SEGMENTATION_SOURCE: 'SET_VIEWER_SEGMENTATION_SOURCE',
  SET_VIEWER_CROSS_SECTION_SCALE: 'SET_VIEWER_CROSS_SECTION_SCALE',
  SET_VIEWER_CAMERA_POSITION: 'SET_VIEWER_CAMERA_POSITION',
  SET_VIEWER_CAMERA_PROJECTION_SCALE: 'SET_VIEWER_CAMERA_PROJECTION_SCALE',
  SET_VIEWER_CAMERA_PROJECTION_ORIENTATION: 'SET_VIEWER_CAMERA_PROJECTION_ORIENTATION',
  SET_VIEWER_SEGMENTS: 'SET_VIEWER_SEGMENTS',
  SET_VIEWER_SEGMENT_COLORS: 'SET_VIEWER_SEGMENT_COLORS',
  ALERT_ADD: 'ALERT_ADD',
  ALERT_DELETE: 'ALERT_DELETE',
};

export default constants;
